# Site
name: "Tinted Tech"
title: "Tinted Tech"
description: "Learn how to build awesome stuff with practical tutorials"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /imjustablacknerd
google_analytics: 'UA-46278016-1'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jay:
    name: Jay
    display_name: Jay
    email: imjustablacknerd@gmail.com
    web: https://www.imjustablacknerd.github.io
    twitter: https://github.com/imjustablacknerd
    description: "Im an innovative engineer, self-taught and fueled by a love for JavaScript, weaving magic into web technologies with a professional twist."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
